In [3]:
from data import *
from helpers import *
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
# Automated way to create labeled dataset
directory='/../data_gated/'
columns=['FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H']
#columns=['FSC-H', 'SSC-H', 'B530-H', 'B675-H','B572-H','Width']
create_labeled_dataset(directory,columns,label_gated=2,label_not_gated=-1)

# README
## This notebook is useless now that labeling is automated with input

In [2]:
fc_data_all, channels = load_important_data('/GL53_UP_2A.fcs','/../data_gated/all_event')
fc_data_all.channels

('FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H')

In [3]:
fc_data_all, channels = load_important_data('/GL53_UP_2A.fcs','/../data_gated/all_event')
fc_data_all = np.array(fc_data_all)

In [4]:
fc_data_gated, channels = load_important_data('/GL53_UP_2A.fcs','/../data_gated/gated')
fc_data_gated = np.array(fc_data_gated)

In [5]:
print(fc_data_all.shape)
print(fc_data_gated.shape)

(1898, 5)
(879, 5)

In [6]:
#df = pd.DataFrame(data=numpy_data, index=["row1", "row2"], columns=["column1", "column2"])
df_all = pd.DataFrame(data=fc_data_all, columns=['FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H'])
df_gated = pd.DataFrame(data=fc_data_gated, columns=['FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H'])

In [7]:
df_all.loc[:, "hash"] = df_all.apply(lambda x: hash(tuple(x)), axis = 1)
df_gated.loc[:, "hash"] = df_gated.apply(lambda x: hash(tuple(x)), axis = 1)
df_not_gated = df_all.loc[~df_all["hash"].isin(df_gated["hash"]), :]

In [8]:
df_gated.loc[:,"label"] = 1
df_not_gated.loc[:,"label"] = 0

/home/mika/.local/lib/python3.9/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/mika/.local/lib/python3.9/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [35]:

df_final = pd.concat([df_gated, df_not_gated], ignore_index=True).reset_index()
df_final.drop('hash', inplace=True, axis=1)

In [36]:
df_final[df_final['label']==1]

     index    FSC-H    SSC-H   B530-H  B572-H  B675-H  label
0        0  16829.0  67671.0   4424.0  2722.0  5143.0      1
1        1   2087.0   3622.0   4564.0  2096.0  2697.0      1
2        2   1352.0   2325.0   5393.0  2064.0  2340.0      1
3        3   5827.0  12648.0   7840.0  3757.0  5658.0      1
4        4   3123.0   9791.0   8967.0  3483.0  3949.0      1
..     ...      ...      ...      ...     ...     ...    ...
874    874    880.0   7288.0   5985.0  1914.0  1674.0      1
875    875   1715.0   3114.0  14369.0  3673.0  3257.0      1
876    876   3719.0  23087.0   9729.0  2830.0  2522.0      1
877    877   3364.0  29044.0   4371.0  1968.0  1963.0      1
878    878  10154.0  34446.0   8644.0  2582.0  3105.0      1

[879 rows x 7 columns]

In [37]:
df_final[df_final['label']==0]

      index    FSC-H     SSC-H   B530-H  B572-H   B675-H  label
879     879  12471.0   22947.0  22809.0  4506.0   1919.0      0
880     880   1697.0   17593.0  10005.0  2129.0    760.0      0
881     881    809.0   14127.0   6310.0  1168.0    981.0      0
882     882   6045.0   51476.0   3595.0  3499.0   4583.0      0
883     883   1514.0    5699.0  20871.0  4806.0   3657.0      0
...     ...      ...       ...      ...     ...      ...    ...
1893   1893   4514.0   22249.0  34795.0  7520.0   3385.0      0
1894   1894  18603.0  189311.0   7272.0  8321.0  14636.0      0
1895   1895  10527.0   28412.0  10404.0  1801.0    793.0      0
1896   1896   1678.0    9971.0  13940.0  3159.0   1759.0      0
1897   1897  13118.0   23932.0  13972.0  7327.0  13248.0      0

[1019 rows x 7 columns]

In [23]:
y = df_final['label']

In [25]:
X = df_final.drop('label',axis=1)

In [27]:
X, tmp = standardize_log(X)

In [28]:
X

         FSC-H     SSC-H    B530-H    B572-H    B675-H
0     1.097864  1.062997 -0.750120 -0.104689  0.624388
1    -0.612117 -1.579019 -0.713703 -0.449787 -0.094124
2    -0.967767 -1.979077 -0.518615 -0.470103 -0.252174
3     0.229018 -0.450540 -0.081296  0.320850  0.730617
4    -0.281924 -0.681597  0.075699  0.220853  0.330331
...        ...       ...       ...       ...       ...
1893  0.019861  0.059157  1.660601  1.237214  0.158791
1894  1.179965  1.991370 -0.169204  1.370872  1.788536
1895  0.713528  0.279817  0.249439 -0.650093 -1.456657
1896 -0.790805 -0.665157  0.591419  0.091920 -0.569863
1897  0.893787  0.124963  0.594099  1.202881  1.677628

[1897 rows x 5 columns]

In [81]:
#Summary

#Files
file = '/GL53_UP_2A.fcs'
folder_all = '/../data_gated/all_event'
folder_gated = '/../data_gated/gated'

#Load to DataFrame
fc_data_all, channels = load_important_data(file,folder_all)
fc_data_all = np.array(fc_data_all)
df_all = pd.DataFrame(data=fc_data_all, columns=['FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H'])

fc_data_gated, channels = load_important_data(file,folder_gated)
fc_data_gated = np.array(fc_data_gated)
df_gated = pd.DataFrame(data=fc_data_gated, columns=['FSC-H', 'SSC-H', 'B530-H', 'B572-H', 'B675-H'])

#create a hash for each entry to find all entries not gated
df_all.loc[:, "hash"] = df_all.apply(lambda x: hash(tuple(x)), axis = 1)
df_gated.loc[:, "hash"] = df_gated.apply(lambda x: hash(tuple(x)), axis = 1)
df_not_gated = df_all.loc[~df_all["hash"].isin(df_gated["hash"]), :]

#label dataset
df_gated.loc[:,"label"] = 3
df_not_gated.loc[:,"label"] = 1

#concat dataset and remove hash column
#df_final = pd.concat([df_gated, df_not_gated], ignore_index=True)
df_final = df_not_gated.append(df_gated,ignore_index=True)
df_final.drop('hash', inplace=True, axis=1)

#creation of X and y
X = df_final.drop('label',axis=1)
y = df_final['label']

/home/mika/.local/lib/python3.9/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/mika/.local/lib/python3.9/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [82]:
X.shape

(1898, 5)

In [80]:
X

         FSC-H     SSC-H    B530-H    B572-H    B675-H
0     0.852359  0.087033  1.166968  0.560916 -0.472965
1    -0.781574 -0.152734  0.203733 -0.429147 -1.503977
2    -1.388454 -0.350741 -0.335059 -1.221929 -1.219850
3     0.259114  0.816141 -0.992658  0.226916  0.496056
4    -0.875051 -1.169975  1.063178  0.646030  0.244814
...        ...       ...       ...       ...       ...
1893 -1.319540 -0.948030 -0.396868 -0.569725 -0.625003
1894 -0.772931 -1.715395  0.626852  0.291002  0.115875
1895 -0.138835  0.092522  0.171035 -0.053298 -0.168808
1896 -0.221021  0.299671 -0.764205 -0.532985 -0.447731
1897  0.683982  0.453610  0.032821 -0.174405  0.062676

[1897 rows x 5 columns]